### PR TITLE
Migrate to v0.14 API

### PR DESCRIPTION
**Pull request by cosmo0920**

### CODE REVIEW

**Comment by okkez** [comment]
I think you can use `timer_create` plugin helper in this plugin link followings:

```ruby
timer_execute(:out_growthforecast_poster, 0.2) do
  until @queue.empty?
    events = @mutex.synchronize {
      es,@queue = @queue,[]
      es
    }
    # (snip)
  end
end
```

**Comment by cosmo0920** [comment]
> I think you can use timer_create plugin helper in this plugin like followings:

Yeah, you are correct.
But, should we use this plugin helper?
If we use timer plugin helper in this plugin, it creates always timer related instance?
I'd like to create timer instance only if needed.

**Comment by okkez** [comment]
> But, should we use this plugin helper?
> If we use timer plugin helper in this plugin, it creates always timer related instance?

Yes, we should. Because it is important for consistency.
`helpers :timer` introduces some instance variables (empty array and boolean flag), but doesn't create `TImerWatcher` instance.
`TimerWatcher` instance is created when we call `timer_execute`.

**Comment by cosmo0920** [comment]
> `helpers :timer` introduces some instance variables (empty array and boolean flag), but doesn't create TImerWatcher instance.

Umm, I think that more instances variables are introduced when using `helper :timer`.
Because `timer` plugin helper includes `thread` plugin helper, and `thread` plugin helper includes `event_loop` plugin helper.
Is my understanding of plugin helper lifecycle incorrect?

**Comment by cosmo0920** [comment]
Hm, output plugin base class already uses thread plugin helper. :confounded:

**Comment by tagomoris** [comment]
@cosmo0920 What is your are considering about? Using plugin helpers itself doesn't so much resources.
Anyway, the purpose of thread in this plugin is posting HTTP request in another thread, and it can be implemented as buffered output plugin.

The solution is:

* override `prefer_buffered_processing` to return true If `background_post` is enabled
* define `process` like existing `#emit` without code related with `@thread`
* define `format` to generate `events` and return `events.to_msgpack`
* define `write` to execute `msgpack_each` to get `events`, and post it

Threads will be created by `output.rb` only when needed, and plugin code doesn't create any threads or timers.
(it's better to set very short value for `flush_interval`.)

**Comment by cosmo0920** [comment]
Currently, I have no idea to convert this plugin as buffered output plugin.
Because I don't understand fully following behaviour and meanings:

* prefer_* method meaning and effects
* `chunk#msgpack_each` in v0.14
  * sometimes yielded `time, record` or `tag, time, record`
      - Probably, it caused by misunderstanding of `<buffer CHUNK_KEY>` specification
* Sometimes I feel that plugin helpers are inconvenient
  * Perhaps it caused by lack of their documentations
      - I often fall their pitfalls... :cry:

**Comment by tagomoris** [comment]
I created a branch to show an example of migration of this plugin.
https://github.com/tagomoris/fluent-plugin-growthforecast/pull/23

Can this help you?

**Comment by cosmo0920** [comment]
> I created a branch to show an example of migration of this plugin.
> #23
> 
> Can this help you?

Yes, very helpful for me.
But I didn't understand why you use `chunk.extend Fluent::ChunkMessagePackEventStreamer` in `#write` at #23.
This hack is for performance?

**Comment by tagomoris** [comment]
Currently (in Fluentd v0.14.6), chunks in `#write` don't have method `#each` to read data from chunk body, except for standard format plugins (which don't have `#format` method).
But if `#format` returns msgpack binary data, it can be unpacked and iterable via ChunkMessagePackEventStreamer.

I'm writing a patch of Fluentd to do `extend ChunkMessagePackEventStreamer` for such plugins (which returns msgpack binary from `#format`), but currently, that `extend` is needed.

**Comment by cosmo0920** [comment]
Umm, #23's implementation does not handle `:data` field in gf event correctly....

**Comment by tagomoris** [comment]
I'll merge this at first, then add some fix for updated v0.14 features.
Thank you @cosmo0920 !

**Comment by cosmo0920** [comment]
Yay!

**Pull request merged**
